def generate_arc(current_chapter):
    arcs = {"Romance Dawn": [i for i in range(1, 8)],
        "Orange Town": [i for i in range(8, 22)],
        "Syrup Village": [i for i in range(22, 42)],
        "Baratie": [i for i in range(42, 69)],
        "Arlong Park": [i for i in range(69, 96)],
        "Loguetown": [i for i in range(96, 101)],
        "Reverse Mountain": [i for i in range(101, 106)],
        "Whiskey Peak": [i for i in range(106, 115)],
        "Little Garden": [i for i in range(115, 130)],
        "Drum Island": [i for i in range(130, 155)],
        "Arabasta": [i for i in range(155, 218)],
        "Jaya" : [i for i in range(218, 237)],
        "Skypeia" : [i for i in range(237, 303)],
        "Long Ring Long Land" : [i for i in range(303, 322)],
        "Water 7" : [i for i in range(322, 375)],
        "Enies Lobby" : [i for i in range(375, 431)],
        "Post-Enies Lobby" : [i for i in range(431, 442)],
        "Thriller Bark" : [i for i in range(442, 490)],
        "Sabaody Archipelago" : [i for i in range(490, 514)],
        "Amazon Lily" : [i for i in range(514, 525)],
        "Impel Down" : [i for i in range(525, 550)],
        "Marineford" : [i for i in range(550, 581)],
        "Summit War: Post-War" : [i for i in range(581, 598)],
        "Return to Sabaody" : [i for i in range(598, 603)],
        "Fish-man Island" : [i for i in range(603, 654)],
        "Punk Hazard" : [i for i in range(654, 700)],
        "Dressrosa" : [i for i in range(700, 802)],
        "Zou" : [i for i in range(802, 825)],
        "Whole Cake Island" : [i for i in range(825, 903)],
        "Levely" : [i for i in range(903, 909)],
        "Wano Country" : [i for i in range(909, current_chapter)]
        }
    return arcs